/**************************************************
*    Author: Frank Dockhorn
*    Copyright 2001 - 2006
*    Application: Four wins
***************************************************/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_0005falphabeta_alphabeta_0005fbackend_GameEngineAdapter */
#ifndef _GAME_ENGINE_ADAPTER
#define _GAME_ENGINE_ADAPTER

#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameAgent_initializeListsJNI
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameAgent_iterativeDeepeningJNI
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_updateStatusJNI
  (JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameAgent_fillSearchResultsJNI
  (JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_undoMoveJNI
  (JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_doMoveJNI
  (JNIEnv *, jclass, jobject, jbyte);

JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_setTimeOutJNI
  (JNIEnv *, jclass, jint);

JNIEXPORT jint JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_getBoardscoreJNI
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_getCountJNI
  (JNIEnv *, jclass);

JNIEXPORT jlong JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_getHashKeyJNI
  (JNIEnv *, jclass);

JNIEXPORT jlong JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_getRevKeyJNI
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_setSideJNI
  (JNIEnv *, jclass, jbyte);

JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_initializeGameboardJNI
  (JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL Java_project_1alphabeta_alphabeta_1backend_GameEngineAdapter_getVersionJNI
  (JNIEnv *, jclass, jobject);

JNIEXPORT jobjectArray JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_checkFinalWinJNI
(JNIEnv* env, jclass cls, jobject position);

JNIEXPORT int JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_freePositionsJNI
(JNIEnv* env, jclass cls);

JNIEXPORT jdouble JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameAgent_getHashtableMemoryDemandJNI
(JNIEnv* env, jclass cls);

JNIEXPORT jboolean JNICALL Java_project_1alphabeta_alphabeta_1backend_WinGameboard_lookupBookMoveJNI
(JNIEnv* env, jclass cls, jstring path, jobject position);

#ifdef __cplusplus
}
#endif
#endif
